[package]
name = "hello"
version = "0.1.0"
authors = ["Voro Oller <voro.oller@couragium.com>"]
edition = "2018"

[dependencies]
tide = "0.15"
async-std = { version = "1.8", features = ["attributes"] }
